services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_vol:/data/db

volumes:
  mongodb_vol: { }